version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: rails-user 
      POSTGRES_PASSWORD: password 
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://rails-user:password@db:5432/rails-ships